server:
  port: 8080
spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: stockModule
          uri: lb://StockService
          predicates:
            - Path= /stocks/**
        - id: productModule
          uri: lb://ProductService
          predicates:
            - Path= /product/**
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


