server:
  port: 8081
spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        - id: reportingModule
          uri: lb://ReportingService
          predicates:
            - Path= /reports/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


